### ISSUE TITLE
Requests: Display Stream titles, Import/Export Feature, don't show "0" above the Icon

### ISSUE THREAD

**Issue by 0lhi** [craftamap/owncast-browser-extension#210]
- [x] #213
- [x] #212
- [x] #211
![OwnCastAddOn](https://user-images.githubusercontent.com/74732674/146468374-6a369605-2ec5-4036-b627-b6c2fabe2154.png)

**Comment by craftamap** [comment]
Thanks for the feature requests - I will look into them soon :)

**Comment by craftamap** [comment]
v0.5.0 just got released and contains all the features.  It's is already live for firefox, chrome is pending :)
