### ISSUE TITLE
Logging in the console

### ISSUE THREAD

**Issue by gabek** [craftamap/owncast-browser-extension#56]
As I'm working on Owncast and looking in the browser console I'll often see messages from the extension, and I'll think they're messages coming from Owncast for a second :)  Can these messages be removed for release builds?

**Comment by craftamap** [comment]
Hey @gabek ,

Thanks for reporting this. I wanted to do this as well, so I will remove them in the next days :)

**Comment by craftamap** [comment]
This should be solved by https://github.com/craftamap/owncast-browser-extension/releases/tag/v0.3.0 (already released for firefox, chrome release pending)
